documents:
  - code: "000"
    official_code: "CEVA-RHYAD-000-MODELE"
    revision: "Rev0.1"
    family: "000"
    source: "config/documents/000.yaml"

  - code: "001"
    official_code: "CEVA-RHYAD-001-CHARTE"
    revision: "Rev0.1"
    family: "000"
    source: "config/documents/001.yaml"

  - code: "001A"
    official_code: "CEVA-RHYAD-001A-ACAP"
    revision: "Rev0.1"
    family: "000"
    source: "config/documents/001A.yaml"

  - code: "002"
    official_code: "CEVA-RHYAD-002-PF"
    revision: "Rev0.1"
    family: "000"
    source: "config/documents/002.yaml"

  - code: "003"
    official_code: "CEVA-RHYAD-003-GLOSSAIRE"
    title: "Glossaire"
    revision: "Rev0.1"
    family: "000"
    source: "config/documents/003.yaml"

  - code: "004"
    official_code: "CEVA-RHYAD-004-REGISTRE DES RISQUES"
    title: "Registre des Risques"
    revision: "Rev1.0"
    status: "Validated"
    family: "000"
    source: "config/documents/004.yaml"

  - code: "005"
    official_code: "CEVA-RHYAD-005-REGISTRE DES DECISIONS"
    title: "Registre des Décisions"
    revision: "Rev1.0"
    status: "Validated"
    family: "000"
    source: "config/documents/005.yaml"

  - code: "006"
    official_code: "CEVA-RHYAD-006-PDD"
    title: "Plan Directeur Documentaire"
    revision: "Rev1.0"
    status: "Validated"
    family: "000"
    source: "config/documents/006.yaml"

  - code: "MTH01"
    official_code: "CEVA-RHYAD-000-MTH01"
    title: "Guide Méthodologique RHYAD"
    revision: "Rev1.0"
    status: "Validated"
    family: "000"
    source: "config/documents/MTH01.yaml"

  - code: "F01"
    official_code: "CEVA-RHYAD-100-F01"
    title: "Réception et Expédition"
    revision: "Rev1.0"
    status: "Validated"
    family: "100"
    source: "config/documents/functions/F01.yaml"
